# Generated by Django 5.2.4 on 2025-07-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_birth_date_profile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
