# Generated by Django 5.2.4 on 2025-07-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_saved_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_money',
        ),
    ]
