# Generated by Django 5.2.4 on 2025-07-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_saved_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
