# Generated by Django 5.2.4 on 2025-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_saved_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
