# Generated by Django 5.2.4 on 2025-07-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('mood', models.CharField(choices=[('GR', 'Great'), ('GO', 'Good'), ('N', 'Neutral'), ('D', 'Difficult'), ('S', 'Struggling')], default='Neutral', max_length=15)),
                ('triggers', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.profile')),
            ],
        ),
    ]
