# Generated by Django 5.2.4 on 2025-07-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
