# Generated by Django 5.2.4 on 2025-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_journal_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='mood',
            field=models.CharField(choices=[('A', 'Great'), ('B', 'Good'), ('C', 'Neutral'), ('D', 'Difficult'), ('E', 'Struggling')], default='Neutral', max_length=15),
        ),
    ]
