# Generated by Django 5.2.4 on 2025-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_journal_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='mood',
            field=models.CharField(choices=[('Great', 'Great'), ('Good', 'Good'), ('Neutral', 'Neutral'), ('Difficult', 'Difficult'), ('Struggling', 'Struggling')], default='Neutral', max_length=10),
        ),
    ]
