# Generated by Django 5.2.4 on 2025-07-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_journal_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='app.profile'),
        ),
    ]
