# Generated by Django 5.2.4 on 2025-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_journal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='triggers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
