# Generated by Django 5.2.4 on 2025-07-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_journal_triggers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='journal',
            name='triggers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
