# Generated by Django 5.2.4 on 2025-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_created_at_journal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
