# Generated by Django 5.2.4 on 2025-07-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_journal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='description',
            new_name='content',
        ),
    ]
