# Generated by Django 5.2.4 on 2025-07-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_description_journal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
