# Generated by Django 5.2.4 on 2025-07-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_goal_completed_alter_goal_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
