# Generated by Django 5.2.4 on 2025-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_created_at_goal_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
