# Generated by Django 5.2.4 on 2025-07-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_cravings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cravings',
            new_name='Craving',
        ),
    ]
