# Generated by Django 5.2.4 on 2025-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_cravings_craving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
