# Generated by Django 5.2.4 on 2025-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_profile_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
